### ISSUE TITLE
extension functions

### ISSUE THREAD

**Issue by K0zka** [seratch/kotliquery#1]
This is just raw idea, how about adding extension functions to existing JDBC interfaces so that users could reuse the library in existing JDBC frameworks such as spring-jdbc?

e.g.

```
fun ResultSet.row() = Row(this, ...)
```

**Comment by seratch** [comment]
When can our original `Row` value be useful for other JDBC libraries? I'm not sure what the use case is. And I'm also wondering if just adding an extension function to ResultSet is efficient for the purpose.
