### ISSUE TITLE
Add support for named parameters

### ISSUE THREAD

**Issue by esaounkine** [seratch/kotliquery#10]
It would be a whole lot more convenient to have named parameters in the queries instead of `?`.

Especially this makes sense when one has to use the same param more than once in a query.

For instance, instead of

```sql
SELECT * FROM table t WHERE (? IS NULL OR t.a = ?) AND (? IS NULL OR t.b = ?)
```

would be nice to write

```sql
SELECT * FROM table t WHERE (:param1 IS NULL OR t.a = :param1) AND (:param2 IS NULL OR t.b = param2)
```

and to pass parameters in a map, e.g.

```kotlin
mapOf(
    "param1" to param1,
    "param2" to param2
)
```

**Comment by seratch** [comment]
PR #15 has been merged.

**Comment by esaounkine** [comment]
Awesome, thanks!

Could you please also create a tag/release on GH so it'd become possible to use this version in projects :)

**Comment by seratch** [comment]
version 1.1.4 is out. Thank you for your great contributions 👍
