### ISSUE TITLE
Support NULL values in query params

### ISSUE THREAD

**Issue by esaounkine** [seratch/kotliquery#12]
Nullable columns in the DB currently can't be optionally filled during insert into the table.

For instance, let's assume a table:

```sql
CREATE TABLE test (
  id      VARCHAR(10),
  name    VARCHAR(20),
  PRIMARY KEY(id)
)
```

Somewhere in the code later, I'll have a function to insert rows:

```kotlin
fun createTestRow(id: String, name: String?) {
  using(sessionOf(HikariCP.dataSource())) { session ->
    session.run(queryOf("INSERT INTO test (id, name) VALUES (?, ?)", id, name).asUpdate)
  }
}
```

Obviously, `name` cannot be used the way I've put it here, as `queryOf` expects params of type `Any`. 

The logic that I'm trying to accommodate includes an empty `name` though, so it'd be nice to pass `null` references.

**Comment by seratch** [comment]
Hmm, that's true. Do you have implementation ideas to fix this?

**Comment by esaounkine** [comment]
Actually, it seems possible right out of the box with a small change to your current implementation.

Let me just add a couple tests.

**Comment by seratch** [comment]
#13 has been merged.
