### ISSUE TITLE
Bad support for `null` parameters in PortgreSQL

### ISSUE THREAD

**Issue by esaounkine** [seratch/kotliquery#14]
The issue has been described in 2011 [here](https://www.postgresql.org/message-id/6ekbd7dm4d6su5b9i4hsf92ibv4j76n51f@4ax.com) and I've just stumbled upon it in my project using kotliquery.

There's a suggested way around it, using `PreparedStatement.setObject(id, null, type)` instead of `PreparedStatement.setObject(id, null)`.

**Comment by seratch** [comment]
I have not encountered such a problem while using PostgreSQL. Does the issue occur with old versions?

**Comment by esaounkine** [comment]
Me neither, first time it occurred was yesterday. I use version `42`.

E.g. imagine a query
```sql
select * where ? is null OR 1 = ?
```
where both `?` will be substituted by the same param. The second param will have no problem, whilst the first one will fail with `ERROR: could not determine data type of parameter $1`.
In my PR I've included a test that will fail if you just copy it into your `master` branch and connect to a PostgresSQL.

**Comment by seratch** [comment]
I see. You mean the use case having `where ? is null`, specifically. I am not willing to change the default implementation to support such queries. If you introduce some switching flag to use `setNull` instead, it would be acceptable for me.

**Comment by esaounkine** [comment]
I've tried some pattern matching, but all approaches involved quite heavy interface changes (like providing explicit type of the `null` variable).
So it seems to me that, sadly, I'll have to find a way around :( Maybe I'll give another try to some switching variants.
Just to mention though, it is a valid SQL syntax, but also it is a pretty [common practice](https://stackoverflow.com/questions/4215135/how-to-deal-with-maybe-null-values-in-a-preparedstatement). But that's really your call.

**Comment by esaounkine** [comment]
I've submitted a version with explicit type specification. Up to you from here :)

**Comment by seratch** [comment]
Thanks, the typed params implementation looks pretty nice. 👍

**Comment by esaounkine** [comment]
Awesome, thank you! Please create a new version.

**Comment by seratch** [comment]
@esaounkine kotliquery 1.1.5 has been released with your changes. Thank you for your contribution 🎉
