### ISSUE TITLE
Possible defect in initializing connection with same name in HikariCP.kt

### ISSUE THREAD

**Issue by izzyreal** [seratch/kotliquery#25]
In line 25 we check if a connection of a given name already exists. If it does, we check if it is already closed: if (existing != null && existing.isClosed)

If those conditions are satisfied, the connection is attempted to be closed on line 26: existing.close()

Seems to me line 25 should check if the connection is NOT closed.

**Comment by seratch** [comment]
Thanks! I've fixed this issue in the latest revision
