### ISSUE TITLE
Support batched queries

### ISSUE THREAD

**Issue by stoyle** [seratch/kotliquery#26]
Hey. First off, been using kotliquery for almost a year, and it is working great for us. Like that it is just a relative small wrapper around jdbc, so thanks for your work.

We have seen the need for batched queries, specifically batched inserts. Which I cannot see kotliquery supporting at the moment. Would that be a feature you would be interested in adding?

We've implemented it ourselves, for our specific purpose, but I would be happy to contribute some code back.

If not, could you make `private inline fun <reified T> PreparedStatement.setTypedParam(idx: Int, param: Parameter<T>)` public? This is the only part of the kotliquery code we had to copy to make it work for us.

Cheers,
Alf

**Comment by seratch** [comment]
It's great to hear that! Thank you for choosing my library.

>We've implemented it ourselves, for our specific purpose, but I would be happy to contribute some code back.

I will welcome your contribution. Having batch operations support in the library is reasonable enough.

**Comment by stoyle** [comment]
Nice!

Will create a PR, when time permits :) Hopefully this weekend, but at least before x-mas...

Cheers,
Alf

**Comment by stoyle** [comment]
This has been release, thanks :)
