### ISSUE TITLE
Named parameters with array type

### ISSUE THREAD

**Issue by rubendm92** [seratch/kotliquery#27]
Hi

We are trying to do an insert to a table that contains a field of type text[] (postgres). We are doing something like this
```kotlin
sessionProvider.createSession().use { session ->
    session.run(queryOf(
            "INSERT INTO t(x, xs) VALUES(:x, :xs)",
            mapOf("x" to "hello", "xs" to listOf("1", "2"))
    ).asUpdate)
}
```

We are getting an error because of the type os `xs`.

`org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of java.util.Collections$SingletonList. Use setObject() with an explicit Types value to specify the type to use.`

I don't see any example or documentation related to this. Is this supported?

Thanks!

**Comment by seratch** [comment]
Use `java.sql.Array` type for array type. It's not due to a specification of this library but JDBC's one. https://jdbc.postgresql.org/documentation/head/arrays.html

**Comment by rubendm92** [comment]
But for creating a `java.sql.Array` I need a JDBC's connection, right? All the examples I see are using a connection from JDBC but I don't see how to do it with the session object from Kotliquery or something similar

**Comment by rubendm92** [comment]
Oh, I see I can use `session.connection.underlying.createArray`. Kinda ugly, don't you think? 🤔

**Comment by seratch** [comment]
I agree. It's also not ideal but I'm okay to have `session.createArray` in short.
