### ISSUE TITLE
Condiser using stringOrNull instead of  "!!"

### ISSUE THREAD

**Issue by erictsangx** [seratch/kotliquery#4]
Hi @seratch,
I think in reality we have more non-null data than nullable data, it is handier and more readable if default function return non-null type:

``` kotlin
fun string() : String { ... }
fun stringOrNull: String? { ... }
```

`kotlin.collections` also use this pattern such as `single` and `singleOrNull`.

I would like to submit a PR if you agree on this.

**Comment by seratch** [comment]
As you suggested, `xxxOrNull` naming looks straightforward in Kotlin. https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/index.html

> I would like to submit a PR if you agree on this.

Fair enough. I'm looking forward to merging your PR. :+1:

**Comment by seratch** [comment]
I've done this API changes. Try version 1.1.0.
