### ISSUE TITLE
session 'run' and 'execute' always returns false for 'create table' request

### ISSUE THREAD

**Issue by Tolsi** [seratch/kotliquery#40]
You can check it for example here:

https://github.com/seratch/kotliquery/blob/252016a5c25acbf569aa579c2daed116b1a9caac/sample/src/main/kotlin/Example.kt#L9-L15

**Comment by seratch** [comment]
It's because of the JDBC specification.

>true if the first result is a ResultSet object; false if the first result is an update count or there is no result

https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#execute-java.lang.String-

**Comment by Tolsi** [comment]
Can I check somehow that the table was created?

**Comment by seratch** [comment]
If it fails, an exception would be thrown.
