### ISSUE TITLE
Why is count function not running ?

### ISSUE THREAD

**Issue by raul1991** [seratch/kotliquery#43]
# What do I want to do ?
To count the rows returned by the query

# What works ?
```
session.run(queryOf("select * from table-1").map { it.count() }.asSingle)
```

# Expected
```
session.run(queryOf("select count(1) from table-1").map { it.int(0) }.asSingle)
```

Am I doing anything wrong ?

**Comment by raul1991** [comment]
One more thing, I guess I need to add 1 to the count above ? Since the sequence.count() in the map function returns me 1 less than actual count.
I guess this has something to do with the iteration you do in the Row class ?

**Comment by seratch** [comment]
As the `Row` class represents a JDBC's ResultSet object, which is an stateful iterator, I don't recommend using Sequence's count method. The recommended way is to use  the `count` function in the SQL statement as you did in the "Expected" section.

Another solution would using foreach method and accumulating the count this way: https://github.com/seratch/kotliquery/blob/1.3.1/src/test/kotlin/kotliquery/UsageTest.kt#L59-L64

**Comment by raul1991** [comment]
If I use the one in the expected section , it returns me a 0 always.

**Comment by seratch** [comment]
It's a JDBC specification. the index number is 1 origin. https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html#getInt(int)

**Comment by seratch** [comment]
Let me close this issue now but feel free to write in if you have any follow ups!
