### ISSUE TITLE
java.time.Instant stored without nanoseconds

### ISSUE THREAD

**Issue by ievgen-kapinos** [seratch/kotliquery#48]
In `Session.kt` in `fun PreparedStatement.setParam(idx: Int, v: Any?)` we have
```
is Instant -> this.setTimestamp(idx, Timestamp(Date.from(v).time))
```

In result `Instant` is converted to `Date`, and than to `Timestamp`

`Instant` and `Timestamp` support nanoseconds, 
But `Date` does not. So value is truncated.
We can map value directly using `Timestamp.from(Instant)`

Another issue in same function
```
when (v) {
  ...
  is java.util.Date -> this.setTimestamp(idx, Timestamp(v.time))
  is java.sql.Timestamp -> this.setTimestamp(idx, v)
  ...
```
`Timestamp` in sub class of `Date`. So `Timestamp` is not executed. And we loose nanos here as well 

P.S. Thanks for great lib!

**Comment by ievgen-kapinos** [comment]
Is this project alive?

**Comment by seratch** [comment]
Hi @ievgen-kapinos, thanks for the suggestion! I overlooked this issue. You are right here. These can be improved in future releases. If you are happy to make PRs, your contributions would be greatly appreciated.
