### ISSUE TITLE
This is not an issue, just q question

### ISSUE THREAD

**Issue by sitexa** [seratch/kotliquery#5]
fun getMemberById(id: String): Member? {
     val aMember = using(sessionOf(dataSource)) { session ->
     val query = queryOf("select \* from t_member where id = ?", id).map {toMember}.asSingle
     val maybeMember = query.runWithSession(session)
     }
     return aMember???
}

The question is , how can I return a member?

**Comment by seratch** [comment]
I'm not sure what your question is. Please see the example code: https://github.com/seratch/kotliquery/blob/master/src/test/kotlin/kotliquery/UsageTest.kt
