### ISSUE TITLE
Update query with RETURNING not invoking `extractor.invoke(row)`

### ISSUE THREAD

**Issue by Somnium99** [seratch/kotliquery#54]
I have a simple query : 
```
UPDATE  boards
SET     version = version + 1
WHERE   id = :boardId
AND     version = :boardVersion
RETURNING id, version, modified_at
```

while debugging I can see it's just skipping `extractor.invoke(row)` in this function : 
```
 private fun <A> rows(query: Query, extractor: (Row) -> A?): List<A> {
        return using(createPreparedStatement(query)) { stmt ->
            using(stmt.executeQuery()) { rs ->
                val rows = Row(rs).map { row -> extractor.invoke(row) }  <-------- skipping this invoke
                rows.filter { r -> r != null }.map { r -> r!! }.toList()
            }
        }
    }
```
This results in null response of course.

my code is as follows : 
```
 return tx.run(queryOf(stmt, params)
                .map( { row -> .......... } )
                .asSingle)

```

I also tried using .asList , but it still skips the extractor.invoke

**Comment by seratch** [comment]
Sorry for my belated response here. This library does not support multiple columns in the returning statement. If you return only ID, you can use updateAndReturnGeneratedKey for it. Let me close this issue now.
