### ISSUE TITLE
How to get auto-generated ID following an Insert?

### ISSUE THREAD

**Issue by codemwnci** [seratch/kotliquery#8]
Using the example code as an example
```
val insertQuery: String = "insert into members (name,  created_at) values (?, ?)"

session.run(queryOf(insertQuery, "Alice", Date()).asUpdate) // returns effected row count
session.run(queryOf(insertQuery, "Bob", Date()).asUpdate)
```

How can we get hold of the statement that executed the query to be able to get the auto-generated ID? The asUpdate returns the effected row count, so in the example will always return 1.

**Comment by seratch** [comment]
Currently, it's unsupported.

**Comment by codemwnci** [comment]
I have created a pull request that implements this. Limitations to my pull request however
- only returns the first key, regardless of how many keys there are
- only returns the key as a Long
